spring:
  application:
    name: zuul

server:
  port: 4000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 2

# 设置默认超时时间60s（default为全局；若想设置某项服务的超时时间，只需要将default替换为对应的服务名）
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
zuul:
  addHostHeader: true
  routes:
    userservice:
      path: /userservice/**
      serviceId: userservice
      sensitiveHeaders:
      customSensitiveHeaders: true
    wantrip:
      path: /wantrip/**
      serviceId: wantrip
      sensitiveHeaders:
      customSensitiveHeaders: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

eureka:
  instance:
    hostname: config
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.118:8762/eureka/