spring:
  application:
    name: eureka

server:
  port: 8762

eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
