spring:
  application:
    name: userservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trip?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456
    initialize: true
    sql-script-encoding: utf-8

server:
  port: 8083

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.userservice.dao
